### ISSUE TITLE
segmentation fault while running `gazetool`

### ISSUE THREAD

**Issue by rezaahmadzadeh** [lschilli/gazetool#3]
After compiling and installing the whole project, I get `Segmentation fault (core dumped)` when running `gazetool` on the computer. I could follow the fault up to this line:
`GazerGui gui;`
in the _main.cpp_, it happens when instantiating the object _gui_. What do you suggest? 
- Ubuntu 14.04 LTS 64bit
- Boost 1.55
- OpenCV 2.4.11
- dlib 18.18-
- Qt5

Please let me know, if you need further information.

**Comment by lschilli** [comment]
Thanks for your feedback. Can you provide the command line you used to start run the tool? Can you check if opengl is functional on your testing machine i.e. glxgears is working? It seems something goes wrong during gui construction.

**Comment by rezaahmadzadeh** [comment]
Thank you for the quick reply!
The result is the same for the following commands:

> gazetool.sh -c 0
> gazetool

`$ gazetool.sh -c 0`
`Segmentation fault (core dumped)`

`glxgear` works and the final output is normal:

> Running synchronized to the vertical refresh.  The framerate should be
> approximately the same as the monitor refresh rate.
> 325 frames in 5.0 seconds = 64.874 FPS

I have also the following libraries installed, which I mentioned as side info.
- lapack 3.5.0
- blas 1.2.20110419

**Comment by lschilli** [comment]
Tomorrow I still will be at the IIT: https://www.codefror.eu/events
What about meeting during a break?
The error seems like a QT related problem. Can you post a full stack trace of the crashing thread?

**Comment by rezaahmadzadeh** [comment]
It would be great if you can pass by. I will be at IIT from 10:00 till 17:00. Let me know, when you can. By the way, I sit just besides the blue iCub (3rd floor - iCub Facility).

**Comment by lschilli** [comment]
Notes after fixing locally:
The segfault occurs when glclearcolor is called. Initialization needs to be adapted for qt 5.4
See: https://forum.qt.io/topic/50726/solved-calling-opengl-functions-in-a-qt-program-qt-5-4

Workaround:
comment out `qglClearColor(bgColor);` in `glimageview.cpp:14`

**Comment by rezaahmadzadeh** [comment]
Now it works like a charm.
Thank you very much for the fix and especially for the local support!
