### ISSUE TITLE
Where do i put dlib

### ISSUE THREAD

**Issue by atv2016** [lschilli/gazetool#7]
Not sure how to link against dlib, i put it in the source directory but it's not finding it. It keeps asking for:

$ cmake .
CMake Error at CMakeLists.txt:11 (FIND_PACKAGE):
  By not providing "Finddlib.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "dlib", but
  CMake did not find one.

  Could not find a package configuration file provided by "dlib" with any of
  the following names:

    dlibConfig.cmake
    dlib-config.cmake

  Add the installation prefix of "dlib" to CMAKE_PREFIX_PATH or set
  "dlib_DIR" to a directory containing one of the above files.  If "dlib"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!

**Comment by atv2016** [comment]
I tried this but same message: cmake -DDLIB_PATH=<path to dlib> ..

**Comment by lschilli** [comment]
dlib needs to be installed by running `make install`.
The prefix can be arbitrary. E.g. `CMAKE_INSTALL_PREFIX=/some/path`
cmake find_package heuristics will find dlib in many cases, e.g. if the path environment has been extended by `PATH=$PATH:/some/path/bin`
