### ISSUE TITLE
Very low frame rates

### ISSUE THREAD

**Issue by GeorgeMarkham** [lschilli/gazetool#8]
Hi I'm running Gazetool on a machine with an i5, 8Gb of RAM and a GTX 750ti on Ubuntu 16.04 but it's reporting frame rates of 0fps, I've tried the troubleshooting methods outlined in the readme but framerates have not improved, is there anything else I can try to optimise the program?

Thanks for your help.

**Comment by lschilli** [comment]
Are you sure that you included `-march=native -O3` in CMAKE_CXX_FLAGS?
Can you run `make clean` and subsequently run `VERBOSE=1 make` and post the results here?

If you run top, how much %CPU load is displayed for Gazetool (approximately?)

**Comment by GeorgeMarkham** [comment]
Thanks for your help, I just fixed the issue, it turns out I hadn't properly set the CMAKE_CXX_FLAGS. Really appreciate the quick response, thank you.

**Comment by lschilli** [comment]
Great, glad I could help.
